name: base
channels:
  - bioconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.1.5=py36_0
  - attrs=18.1.0=py36_0
  - bcrypt=3.1.4=py36h14c3975_0
  - beautifulsoup4=4.6.0=py36_1
  - blas=1.0=mkl
  - boost=1.67.0=py36_4
  - bzip2=1.0.6=h9a117a8_4
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36_1
  - cheroot=6.3.2=py36_0
  - click=6.7=py36_0
  - conda=4.6.2=py36_0
  - conda-build=3.10.9=py36_0
  - conda-env=2.6.0=h36134e3_1
  - conda-verify=3.0.2=py36_0
  - cryptography=2.4.2=py36h1ba5d50_0
  - docopt=0.6.2=py36_0
  - docutils=0.14=py36_0
  - dropbox=5.2.1=py36_0
  - filechunkio=1.6=py36_0
  - filelock=3.0.4=py36_0
  - ftputil=3.2=py36_0
  - future=0.16.0=py36_0
  - glob2=0.4.1=py36_0
  - gmp=6.1.2=hb3b607b_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - intel-openmp=2018.0.0=hc7b2577_8
  - jinja2=2.10=py36_0
  - libboost=1.67.0=h46d08c1_4
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=1
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markupsafe=1.0=py36h14c3975_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.2=py36h651fb7a_0
  - mkl_random=1.0.1=py36h4414c95_1
  - more-itertools=4.2.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - numpy=1.14.5=py36h1b885b7_4
  - numpy-base=1.14.5=py36hdbf6ddf_4
  - openssl=1.1.1a=h7b6447c_0
  - packaging=17.1=py36_0
  - pandas=0.23.3=py36h04863e7_0
  - pandocfilters=1.4.2=py36_1
  - paramiko=2.4.1=py36_0
  - patchelf=0.9=0
  - pluggy=0.6.0=py36_0
  - portend=2.3=py36_0
  - psutil=5.4.6=py36h14c3975_0
  - py=1.5.4=py36_0
  - py-boost=1.67.0=py36h04863e7_4
  - pyasn1=0.4.3=py36_0
  - pycosat=0.6.3=py36h14c3975_0
  - pycparser=2.18=py36_1
  - pyinotify=0.9.6=py36_0
  - pynacl=1.2.1=py36h14c3975_0
  - pyopenssl=18.0.0=py36_0
  - pypandoc=1.4=py36_0
  - pyparsing=2.2.0=py36_1
  - pysftp=0.2.9=py36_0
  - pysocks=1.6.8=py36_0
  - pytest=3.6.3=py36_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.12=py36h14c3975_1
  - readline=7.0=ha6073c6_4
  - requests=2.21.0=py36_0
  - ruamel_yaml=0.15.42=py36h14c3975_0
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.26.0=h7b6447c_0
  - tempora=1.11=py36_0
  - tk=8.6.8=hbc83047_0
  - urllib3=1.24.1=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - appdirs==1.4.3
    - argparse==1.4.0
    - backports-functools-lru-cache==1.5
    - configargparse==0.13.0
    - cython==0.28.5
    - datareport==0.1.6
    - datrie==0.7.1
    - django==2.0.5
    - djangorestframework==3.8.2
    - glpi==0.3.1
    - glpi-cli==0.2.0
    - logzero==1.3.0
    - lxml==4.2.4
    - munch==2.2.0
    - mwclient==0.8.7
    - oauthlib==2.1.0
    - pandoc==1.0.2
    - pillow==5.2.0
    - pip==10.0.1
    - pkginfo==1.4.2
    - ply==3.11
    - pygame==1.9.3
    - pygameutils==0.0.4
    - pygments==2.2.0
    - pyparted==3.10.7
    - ratelimiter==1.2.0.post0
    - requests-oauthlib==1.0.0
    - requests-toolbelt==0.8.0
    - ruamel-yaml==0.15.37
    - snakemake==4.8.0
    - snakemakeutils==0.1.2
    - tqdm==4.23.0
    - twine==1.11.0
    - wrapt==1.10.11
    - xlsxwriter==1.1.0
prefix: /home/terhorst/miniconda3

