on: [push]

permissions:
  contents: read

jobs:
  trigger_externals:
    if: ${{ github.repository_owner == 'nest' && github.ref_name == 'master' }}
    name: "Trigger downstream repos"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Trigger nest/nest-extension-module CI
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2.1.2
        with:
          token: ${{ secrets.NEST_EXTENSION_MODULE_TRIGGER_TOKEN }}
          repository: 'nest/nest-extension-module'
          event-type: dispatch-event_nest-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
